import { TOOLS } from "@/lib/tools/registry";
import { generateToolMetadata } from "@/lib/seo/metadata";
import { ToolContainer } from "@/components/tool/ToolContainer";
import { BarcodeGeneratorTool as BarcodeGenerator } from "@/components/tools/lazy-client";
import { notFound } from "next/navigation";
import type { ToolSectionItem } from "@/lib/tools/types";

export const metadata = generateToolMetadata("barcode-generator");

const tool = TOOLS.find((t) => t.slug === "barcode-generator")!;

const howToSteps = [
  "Select the <strong>barcode format</strong> that matches your use case — Code 128 for general text, EAN-13 or UPC-A for retail products, ITF-14 for shipping containers.",
  "Enter the <strong>value to encode</strong>. Each format has specific rules: EAN-13 requires exactly 12 numeric digits; Code 128 accepts any ASCII text; UPC-A requires 11 digits.",
  "Adjust the <strong>bar width, height, and colors</strong> to match your design requirements or branding guidelines.",
  "Toggle the <strong>text label</strong> below the barcode on or off — the label shows the encoded value in human-readable form for manual verification.",
  "Click <strong>Download SVG</strong> to save a scalable vector file that can be resized to any dimensions without quality loss.",
];

const faqs = [
  {
    question: "Which barcode format should I use?",
    answer:
      "<strong>Code 128</strong> is the most versatile — it encodes any ASCII character and is widely used in logistics and general labeling. <strong>EAN-13</strong> and <strong>UPC-A</strong> are used for retail product packaging. <strong>Code 39</strong> is common in manufacturing and healthcare. <strong>ITF-14</strong> is used for shipping cartons and pallets.",
  },
  {
    question: "Why does EAN-13 require 12 digits instead of 13?",
    answer:
      "The 13th digit is a <strong>check digit</strong> calculated automatically from the first 12. Enter the 12 data digits and the barcode will include the correct check digit in both the bars and the label.",
  },
  {
    question: "Can I change the barcode colors?",
    answer:
      "Yes — you can set any color for the bars and the background. For reliable scanning, use <strong>high contrast</strong> between bar and background colors. Black bars on white is the most universally scannable combination.",
  },
  {
    question: "Why use SVG instead of PNG?",
    answer:
      "<strong>SVG is a vector format</strong> that can be scaled to any size — from a tiny label to a large warehouse sign — without becoming blurry or pixelated. This is especially important for barcode quality because precise bar edges are critical for scanner accuracy.",
  },
  {
    question: "Is this tool free?",
    answer: "Yes — completely free with no registration required.",
  },
  {
    question: "Can I scan the generated barcode with a standard scanner?",
    answer:
      "Yes — barcodes generated by this tool use standard encoding that is compatible with <strong>all commercial barcode scanners</strong> and smartphone scanning apps. Ensure adequate size and contrast for reliable scanning.",
  },
  {
    question: "What is the minimum size for a scannable barcode?",
    answer:
      "For reliable scanning, a <strong>1D barcode</strong> should be at least 25mm wide and 15mm tall in print. Smaller barcodes may not scan reliably with all hardware, particularly at distance. The SVG format makes it easy to scale precisely to the required dimensions.",
  },
];

const sections: ToolSectionItem[] = [
  {
    title: "What is a Barcode?",
    content: `<p>A <strong>barcode</strong> is a visual pattern that encodes data in a machine-readable format. The most common type — a <strong>1D (linear) barcode</strong> — represents data as a series of parallel bars and spaces of varying widths. Scanners read the pattern by measuring light reflected off the bars, decoding the widths back into the original data.</p><p>Barcodes are used everywhere in modern commerce, logistics, and healthcare to quickly and accurately capture information without manual data entry. Different barcode formats (called symbologies) are designed for different industries and data types — each has specific rules about what characters can be encoded and how many.</p>`,
  },
  {
    title: "Common Use Cases",
    content: `<p>Barcodes serve critical functions across many industries:</p><ul><li><strong>Retail pricing:</strong> EAN-13 and UPC-A barcodes on product packaging link items to point-of-sale systems for pricing and inventory tracking.</li><li><strong>Warehouse and logistics:</strong> Code 128 and ITF-14 track shipments, pallets, and inventory movement through supply chains.</li><li><strong>Healthcare:</strong> Code 39 and Code 128 are used on patient wristbands, medication packaging, and lab samples to ensure accuracy.</li><li><strong>Asset management:</strong> Businesses label equipment, furniture, and IT assets with barcodes for inventory and audit purposes.</li><li><strong>Event ticketing:</strong> Barcodes on tickets and boarding passes enable fast, accurate verification at entry points.</li></ul>`,
  },
  {
    title: "Tips for Best Results",
    content: `<p>To ensure your barcodes scan reliably:</p><ul><li>Always use <strong>high contrast</strong> — dark bars on a light background. Avoid reversed colors (light bars on dark) unless your scanner explicitly supports it.</li><li>Include a <strong>quiet zone</strong> — a margin of white space on both sides of the barcode. Most standards require a minimum quiet zone of 10 times the narrowest bar width.</li><li>Download as <strong>SVG</strong> and scale to the exact size required for your application — never stretch a PNG barcode as it may distort the bar proportions.</li><li>Test the barcode by scanning it with your actual scanner or app before printing at scale.</li></ul>`,
  },
];

export default function BarcodeGeneratorPage() {
  if (!tool) notFound();
  return (
    <ToolContainer tool={tool} howToSteps={howToSteps} faqs={faqs} sections={sections}>
      <BarcodeGenerator />
    </ToolContainer>
  );
}
